[package]
name = "sniffle-address-macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
litrs = "0.4"
quote = "1.0"
sniffle-address-parse = { path = "../parse" }
