[package]
name = "sniffle-capfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sniffle-core = { path = "../core" }
pcaprs = { path = "../pcaprs" }
